let products = [
    {
        code:1,
        id: 1,
        name: 'Nike Tech Hera',
        image:'dc1dc7e3-5f90-448b-bb06-1876dca86fde.webp',
        option:{
            one: '19bbbf33-f650-4f08-8563-56b3a67ac913.webp',
            two: '31d5f3b3-1a87-43c4-b34d-00058fc96476.webp',
            three: '948fbfa8-d8d1-4baf-a7b3-1dff275608c2.webp',
            four: '8952de2f-3ba3-4eac-8c46-19d89a6cf892.webp',
            five: 'd25c083d-3bb7-4ec2-b1d8-1fac2935716e.webp',
            six: 'ddb56a07-34af-4674-8227-c17bd3d09551.webp',
        },
        price: 110,
        instock: 99,
        size: '',
        description: 'Nothing as fly, nothing as comfortable, nothing as proven. The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle sole, stitched overlays and classic TPU details. Classic colors celebrate your fresh look while Max Air cushioning adds comfort to the journey.',
        shipping: 0,
        color: "3",
        x: 0,
        rating: {
            stars: 4.5,
            count: 87
          },
        model: "Woman's Shoes",
        pickColor: '',
        yellowColor:{
            ops1: 'hera-yellow1.webp',
            ops2: 'hera-yellow1.webp',
            ops3: 'hera-yellow2.webp',
            ops4: 'hera-yellow3.webp',
            ops5: 'hera-yellow4.webp',
            ops6: 'hera-yellow5.webp',
            ops7: 'hera-yellow6.webp',
        },
        grayColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        blackColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        blueColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        redColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
    },
    {
        code:2,
        id: 2,
        name: 'Nike Air Huarache',
        image: '2.webp',
        option:{
            one: 'eaa4acff-b546-4547-868d-2d8c836b807f.webp',
            two: '8981e38c-c28b-439a-b5d7-d7fa0741ed13.webp',
            three: 'ae91a23c-c58e-4bec-8f1a-cc775143a9c3.webp',
            four: 'b75fab6e-b2be-496b-a0b7-6d9e25953031.webp',
            five: 'd6a4ae70-929c-47d6-928e-c495bcc2ae0f.webp',
            six: '9a7149df-4f36-41d6-9778-3b1c4b2fa276.webp',
        },
        price: 125,
        instock: 99,
        size: '',
        description: 'When it fits this good and looks this great, it doesn’t need a Swoosh. From its Crater rubber outsole to its woven, checkerboard textile detailing to its stretchy, “hug your foot” fabric and Nike Air cushioning, the Huarache is bragging rights for your feet.',
        shipping: 0,
        color: "4",
        x: 0,
        rating: {
            stars: 4.5,
            count: 87
          },
        model: "Men's Shoes",
        pickColor: '',
        yellowColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        grayColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        blackColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        blueColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        redColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
    },
    {
        code:3,
        id: 3,
        name: 'LeBron XX',
        image: '3.webp',
        option:{
            one: '57e1545d-2191-477a-b0cb-842590d8ed1a.webp',
            two: '5c4664ca-6401-4a1a-81c2-2599abaa6b16.webp',
            three: '5b3e14a4-b3eb-4864-87cc-1e7d88a35c3c.webp',
            four: '6e5ced8a-f339-440b-b07d-43da36884047.webp',
            five: 'b8886752-b4fc-401d-a1ad-e9f34635c36b.webp',
            six: 'c32ef8c4-6fe4-4098-94d0-d639eb58d3d5.webp',
        },
        price: 210,
        instock: 99,
        size: '',
        description: 'Nearly 2 decades into a career exceeding every lofty expectation, LeBron James has refused to settle for anything less than greatness, even when he was the one setting the standard for generations to come. Now, his latest signature shoe, the LeBron XX (or LeBron 20) is lighter, low to the ground and turbo-like. It’s unlike any design LeBron has donned before—comfortable and supportive, yet low-cut, feathery-fast and created to stay ahead of today’s frenzied style of play.',
        shipping: 0,
        color: "4",
        pickColor: '',
        x: 0,
        rating: {
            stars: 4.5,
            count: 87
          },
        model: "Men's Shoes",
        yellowColor:{
            ops1: 'y1.webp',
            ops2: 'y1.webp',
            ops3: 'y2.webp',
            ops4: 'y3.webp',
            ops5: 'y4.webp',
            ops6: 'y5.webp',
            ops7: 'y6.webp',
        },
        grayColor:{
            ops1: 'g2.webp',
            ops2: 'g2.webp',
            ops3: 'g1.webp',
            ops4: 'g3.webp',
            ops5: 'g4.webp',
            ops6: 'g5.webp',
            ops7: 'g6.webp',
        },
        blackColor:{
            ops1: 'b2.webp',
            ops2: 'b2.webp',
            ops3: 'b1.webp',
            ops4: 'b3.jpg',
            ops5: 'b4.webp',
            ops6: 'b5.webp',
            ops7: 'b6.jpg',
        },
        blueColor:{
            ops1: 'bu1.webp',
            ops2: 'bu1.webp',
            ops3: 'bu2.webp',
            ops4: 'bu3.jpg',
            ops5: 'bu4.webp',
            ops6: 'bu5.jpg',
            ops7: 'bu6.webp',
        },
        redColor:{
            ops1: 'r1.webp',
            ops2: 'r1.webp',
            ops3: 'r2.webp',
            ops4: 'r3.webp',
            ops5: 'r4.webp',
            ops6: 'r5.webp',
            ops7: 'r6.webp',
        }
    },
    {
        code: 4,
        id: 4,
        name: 'Nike Gamma Force',
        image: '4.webp',
        option:{
            one: '1.webp',
            two: '2.webp',
            three: '3.webp',
            four: '4.webp',
            five: '5.webp',
            six: '6.webp',
        },
        price: 90,
        instock: 99,
        size: '',
        description: "Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. Collar materials pay homage to vintage sport while the subtle platform elevates your look, literally. The Gamma Force is forging its own legacy: court style that can be worn all day, wherever you go",
        shipping: 0,
        color: "5",
        x: 0,
        rating: {
            stars: 4.5,
            count: 87
          },
        model: "Woman's Shoes",
        pickColor: '',
        yellowColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        grayColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        blackColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        blueColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        redColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
    },
    {
        code: 5,
        id: 5,
        name: 'Nike Air Max 90 LTR SE',
        image: 'dltr.webp',
        option:{
            one: '1ltr.webp',
            two: '2lltr.webp',
            three: '3ltr.webp',
            four: '4ltr.webp',
            five: '5ltr.webp',
            six: '6ltr.webp',
        },
        price: 130,
        instock: 99,
        size: '',
        description: "Lace up and feel the legacy. Produced at the intersection of art, music and culture, the wardrobe staple that helped define the '90s gets a premium, understated sheen. Keeping the striking visuals you love most: Waffle outsole and exposed Air cushioning, it dons a pique tongue, metallic branding and a durable upper.",
        shipping: 0,
        color: "4",
        x: 0,
        rating: {
            stars: 4.5,
            count: 87
          },
        model: "Big Kid's Shoes",
        pickColor: '',
        yellowColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        grayColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        blackColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        blueColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        redColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
    },
    {
        code: 6,
        id: 6,
        name: 'KD15 "What The"',
        image: '8.webp',
        option:{
            one: '1d15.webp',
            two: '2d15.webp',
            three: '3d15.webp',
            four: '4d15.jpg',
            five: '5d15.webp',
            six: '6d15.webp',
        },
        price: 150,
        instock: 99,
        size: '',
        description: "KD's current catalogue is stacked with heat, always-on-demands and new drops that are hunted after online and thirsted for on social media. We dug into KD's latest inventory and came up with a greatest hits of sorts,.......................... This version is designed for outdoor court use with its extra-durable outsole.",
        shipping: 0,
        color: "3",
        x: 0,
        rating: {
            stars: 4.5,
            count: 87
          },
        model: "Man's Shoes",
        pickColor: '',
        yellowColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        grayColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        blackColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        blueColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
        redColor:{
            ops1: 'cross.png',
            ops2: 'cross.png',
            ops3: 'cross.png',
            ops4: 'cross.png',
            ops5: 'cross.png',
            ops6: 'cross.png',
            ops7: 'cross.png',
        },
    },
];